apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiny-ledger-sa
  labels:
    app.kubernetes.io/name: tiny-ledger
    app.kubernetes.io/part-of: tiny-ledger
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/tiny-ledger-role
